sudo: required
services: 
    - docker
    
    
before_install:
    - docker build -t rohitshar/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true rohitshar/docker-react npm run test
    